// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSkmgZN9TiMyww-vG8Ww7Bw5IqKNhZHHA',
    appId: '1:806143501405:web:d5b1f2eeec167a780059b4',
    messagingSenderId: '806143501405',
    projectId: 'gerenciador-de-projetos-9973b',
    authDomain: 'gerenciador-de-projetos-9973b.firebaseapp.com',
    storageBucket: 'gerenciador-de-projetos-9973b.firebasestorage.app',
    measurementId: 'G-5JGZ336Z72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjmW7RFz22W_pmOBEhhnbdQxWatYi3Ds',
    appId: '1:806143501405:android:f82b1d252fabab540059b4',
    messagingSenderId: '806143501405',
    projectId: 'gerenciador-de-projetos-9973b',
    storageBucket: 'gerenciador-de-projetos-9973b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgYGMidAMHlTquVZQk_ohxp6eFMkB6fY',
    appId: '1:806143501405:ios:79ad7cb6e8cdd14c0059b4',
    messagingSenderId: '806143501405',
    projectId: 'gerenciador-de-projetos-9973b',
    storageBucket: 'gerenciador-de-projetos-9973b.firebasestorage.app',
    iosBundleId: 'com.example.saasgerenciamentogeprojeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgYGMidAMHlTquVZQk_ohxp6eFMkB6fY',
    appId: '1:806143501405:ios:79ad7cb6e8cdd14c0059b4',
    messagingSenderId: '806143501405',
    projectId: 'gerenciador-de-projetos-9973b',
    storageBucket: 'gerenciador-de-projetos-9973b.firebasestorage.app',
    iosBundleId: 'com.example.saasgerenciamentogeprojeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSkmgZN9TiMyww-vG8Ww7Bw5IqKNhZHHA',
    appId: '1:806143501405:web:47875a1daf334fb00059b4',
    messagingSenderId: '806143501405',
    projectId: 'gerenciador-de-projetos-9973b',
    authDomain: 'gerenciador-de-projetos-9973b.firebaseapp.com',
    storageBucket: 'gerenciador-de-projetos-9973b.firebasestorage.app',
    measurementId: 'G-97ZJ6J2Y2R',
  );

}